name: Build and deploy

on:
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build dist
        run: |
          git submodule init && git submodule update
          ./dist.sh
          ls -la

      - name: create release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: "adguardcert-*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true

      - name: upload artifact
        uses: actions/upload-artifact@v3
        if: github.event_name == 'pull_request'
        with:
          name: module build
          path: "adguardcert-*.zip"
