name: Build and deploy

on:
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build dist
        run: |
          ./dist.sh
          ls -la

      - name: create release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: "adguardcert-*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          prerelease: ${{ contains(github.ref, '-') }}

      - name: write PR url
        if: github.event_name == 'pull_request'
        run: |
          echo "${{ github.event.pull_request.html_url }}" > pull_request_url.txt

      - name: upload artifact
        uses: actions/upload-artifact@v3
        if: github.event_name == 'pull_request'
        with:
          name: adguardcert module build
          path: |
            adguardcert-*.zip
            README.md
            pull_request_url.txt

      - name: update json
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          ./update.sh
          git push origin master
          ls -la
