name: Build and deploy

on:
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: nttld/setup-ndk@v1
        id: setup ndk
        with:
          ndk-version: r23
          add-to-path: true

      - name: build dist
        run: ./dist.sh
